apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pde2e-podman
  labels:
    app.kubernetes.io/version: "0.1"
    redhat.com/product: podman-desktop
    dev.lifecycle.io/phase: testing
  annotations:
    tekton.dev/pipelines.minVersion: "0.24.x"
    tekton.dev/categories: podman-desktop, podman
    tekton.dev/tags: podman-desktop, podman, testing
    tekton.dev/displayName: "Podman Preparation Task"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task can setup podman and podman machine on the target host machine

  workspaces:
  - name: pipelines-data
  
  params:
  - name: host
    description: host to connect to the provisioned machine
  - name: username
    description: username to connect to the provisioned machine
  - name: userpassword
    description: user password required to run installers with privileges
  - name: key
    description: key file name to connect to the provisioned machine within the workspace resources path   
  - name: os
    description: type of platform per target host (windows, darwin)
    default: windows
  - name: arch
    description: type of arch per target host for windows only amd64, for darwin amd64 or arm64 
    default: amd64
  - name: workspace-resources-path
    description: path on workspace to find resources to connect to the target machine
  - name: image-version
    description: pde2e-podman image version
    default: '0.0.3'
  - name: download-url
    description: in case we want to download a specific podman version
    default: "''"
  - name: podman-version
    description: podman version (used only by darwin/podman.sh)
    default: "''"
  - name: install-wsl
    description: install WSL on windows
    default: '0'
  - name: podman-initialize
    description: Podman initialization
    default: '0'
  - name: podman-start
    description: Podman machine start param
    default: '0'
  - name: podman-rootful
    description: Initialize rootful podman machine
    default: '0'
  - name: podman-user-networking
    description: Set userModeNetworking flag
    default: '0'
  - name: podman-provider
    description: A podman virtualization provider
    default: "''"
  - name: workspace-qe-subpath
    description: subpath relative to workspace path where results are stored
    default: qe-results
  - name: results-folder
    description: directory for results (matches $resultsFolder in script)
    default: 'results'
  - name: target-cleanup
    description: 'this param controls if folder on target host will be removed'
    default: 'true'

  results:
  - name: duration
    description: total amount of time in seconds for the qe execution
  - name: results-folder-path
    description: path to the results folder
  - name: podman-path
    description: podman path extracted from podman-location.log

  steps:
  - name: pd-e2e-podman
    image: quay.io/odockal/pde2e-podman:v$(params.image-version)-$(params.os)
    imagePullPolicy: Always
    script: |
      #!/bin/bash

      # Prepare ENVs
      SECONDS=0
      TARGET_HOST='$(params.host)'
      TARGET_HOST_USERNAME='$(params.username)'
      TARGET_HOST_KEY_PATH='$(workspaces.pipelines-data.path)'/'$(params.workspace-resources-path)'/'$(params.key)'
      chmod 600 "${TARGET_HOST_KEY_PATH}"
      TARGET_FOLDER=pd-e2e
      TARGET_RESULTS='$(params.results-folder)'
      OUTPUT_FOLDER='$(workspaces.pipelines-data.path)'/'$(params.workspace-resources-path)'/'$(params.workspace-qe-subpath)'
      mkdir -p "${OUTPUT_FOLDER}"
      
      # Create command
      if [[ '$(params.os)' == "windows" ]]; then
        # Removed -podmanVersion because it's not in the PS1 script's param block
        cmd="${TARGET_FOLDER}/podman.ps1 "
        cmd="$cmd -targetFolder '${TARGET_FOLDER}' "
        cmd="$cmd -resultsFolder '${TARGET_RESULTS}' "
        cmd="$cmd -downloadUrl '$(params.download-url)' "
        cmd="$cmd -installWSL '$(params.install-wsl)' "
        cmd="$cmd -initialize '$(params.podman-initialize)' "
        cmd="$cmd -start '$(params.podman-start)' "
        cmd="$cmd -rootful '$(params.podman-rootful)' "
        cmd="$cmd -userNetworking '$(params.podman-user-networking)'"
        if [[ -n '$(params.podman-provider)' ]]; then
          cmd="$cmd -podmanProvider '$(params.podman-provider)' "
        fi
      fi

      if [[ '$(params.os)' == "darwin" ]]; then
        cmd="${TARGET_FOLDER}/podman.sh "
        cmd="$cmd --targetFolder '${TARGET_FOLDER}' "
        cmd="$cmd --resultsFolder '${TARGET_RESULTS}' "
        cmd="$cmd --downloadUrl '$(params.download-url)' "
        cmd="$cmd --version '$(params.podman-version)' "
        cmd="$cmd --installWSL '$(params.install-wsl)' "
        cmd="$cmd --initialize '$(params.podman-initialize)' "
        cmd="$cmd --start '$(params.podman-start)' "
        cmd="$cmd --rootful '$(params.podman-rootful)'"
        if [[ -n '$(params.podman-provider)' ]]; then
          cmd="$cmd --podmanProvider '$(params.podman-provider)' "
        fi
      fi
      
      # Exec
      . entrypoint.sh "${cmd}"

      # Results
      echo -n "${SECONDS}" | tee '$(results.duration.path)'
      
      # Point to the specific log file inside the results folder
      # Your script creates: results/podman-location.log
      LOG_FILE="${OUTPUT_FOLDER}/${TARGET_RESULTS}/podman-location.log"
      
      if [[ -f "$LOG_FILE" ]]; then
        echo -n "$(cat "$LOG_FILE")" | tee '$(results.podman-path.path)'
      else
        echo "Error: Result file $LOG_FILE not found."
        exit 1
      fi
